-- DDL for the OLAP warehouse (DuckDB), star schema: one fact table
-- (fact_sales) around four denormalized dimensions. Unlike the OLTP
-- source, dim_product stores the category NAME directly instead of a
-- category_id, so queries never need to JOIN back to a categories table.
--
-- Executed by src/load.py on every pipeline run.

CREATE TABLE IF NOT EXISTS dim_date (
    date_key   INTEGER PRIMARY KEY,  -- format YYYYMMDD, e.g. 20250314
    full_date  DATE NOT NULL,
    day        INTEGER NOT NULL,
    month      INTEGER NOT NULL,
    month_name VARCHAR NOT NULL,
    quarter    INTEGER NOT NULL,
    year       INTEGER NOT NULL,
    weekday    VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS dim_product (
    product_key INTEGER PRIMARY KEY,  -- surrogate key, generated by the pipeline
    product_id  INTEGER NOT NULL,     -- original id from the OLTP source
    sku         VARCHAR NOT NULL,
    name        VARCHAR NOT NULL,
    category    VARCHAR NOT NULL,     -- denormalized: pulled in from "categories"
    unit_cost   DECIMAL(10, 2) NOT NULL,
    price       DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS dim_customer (
    customer_key INTEGER PRIMARY KEY,  -- surrogate key
    customer_id  INTEGER NOT NULL,
    name         VARCHAR NOT NULL,
    city         VARCHAR NOT NULL,
    country      VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS dim_channel (
    channel_key INTEGER PRIMARY KEY,  -- surrogate key
    channel_id  INTEGER NOT NULL,
    name        VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS fact_sales (
    sale_key        INTEGER PRIMARY KEY,  -- one row per order_item (grain of the fact)
    date_key        INTEGER NOT NULL REFERENCES dim_date (date_key),
    product_key     INTEGER NOT NULL REFERENCES dim_product (product_key),
    customer_key    INTEGER NOT NULL REFERENCES dim_customer (customer_key),
    channel_key     INTEGER NOT NULL REFERENCES dim_channel (channel_key),
    quantity        INTEGER NOT NULL,
    gross_amount    DECIMAL(12, 2) NOT NULL,  -- quantity * unit_price
    discount_amount DECIMAL(12, 2) NOT NULL,  -- gross_amount * discount
    net_amount      DECIMAL(12, 2) NOT NULL,  -- gross_amount - discount_amount
    cost_amount     DECIMAL(12, 2) NOT NULL,  -- quantity * unit_cost
    margin          DECIMAL(12, 2) NOT NULL   -- net_amount - cost_amount
);

-- Indexes on fact_sales' foreign key columns are created separately,
-- after the bulk load - see src/load.py.
