-- DDL (Data Definition Language) for the OLAP data warehouse, in DuckDB.
--
-- This is a STAR SCHEMA: one central fact table (fact_sales) surrounded by
-- small, denormalized dimension tables (dim_date, dim_product, dim_customer,
-- dim_channel). Unlike the OLTP source, dimensions here are intentionally
-- DENORMALIZED - for example dim_product stores the category NAME directly
-- instead of a category_id that points to another table. This means an
-- analytical query like "revenue by category" needs zero JOINs against a
-- separate categories table, which is exactly what makes OLAP (OnLine
-- Analytical Processing) queries fast and simple to write.
--
-- This script is executed by src/load.py every time the pipeline runs.
-- "CREATE TABLE IF NOT EXISTS" makes it safe to run again and again.

CREATE TABLE IF NOT EXISTS dim_date (
    date_key   INTEGER PRIMARY KEY,  -- format YYYYMMDD, e.g. 20250314
    full_date  DATE NOT NULL,
    day        INTEGER NOT NULL,
    month      INTEGER NOT NULL,
    month_name VARCHAR NOT NULL,
    quarter    INTEGER NOT NULL,
    year       INTEGER NOT NULL,
    weekday    VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS dim_product (
    product_key INTEGER PRIMARY KEY,  -- surrogate key, generated by the pipeline
    product_id  INTEGER NOT NULL,     -- original id from the OLTP source
    sku         VARCHAR NOT NULL,
    name        VARCHAR NOT NULL,
    category    VARCHAR NOT NULL,     -- denormalized: pulled in from "categories"
    unit_cost   DECIMAL(10, 2) NOT NULL,
    price       DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS dim_customer (
    customer_key INTEGER PRIMARY KEY,  -- surrogate key
    customer_id  INTEGER NOT NULL,
    name         VARCHAR NOT NULL,
    city         VARCHAR NOT NULL,
    country      VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS dim_channel (
    channel_key INTEGER PRIMARY KEY,  -- surrogate key
    channel_id  INTEGER NOT NULL,
    name        VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS fact_sales (
    sale_key        INTEGER PRIMARY KEY,  -- one row per order_item (grain of the fact)
    date_key        INTEGER NOT NULL REFERENCES dim_date (date_key),
    product_key     INTEGER NOT NULL REFERENCES dim_product (product_key),
    customer_key    INTEGER NOT NULL REFERENCES dim_customer (customer_key),
    channel_key     INTEGER NOT NULL REFERENCES dim_channel (channel_key),
    quantity        INTEGER NOT NULL,
    gross_amount    DECIMAL(12, 2) NOT NULL,  -- quantity * unit_price
    discount_amount DECIMAL(12, 2) NOT NULL,  -- gross_amount * discount
    net_amount      DECIMAL(12, 2) NOT NULL,  -- gross_amount - discount_amount
    cost_amount     DECIMAL(12, 2) NOT NULL,  -- quantity * unit_cost
    margin          DECIMAL(12, 2) NOT NULL   -- net_amount - cost_amount
);

-- NOTE: indexes on the foreign key columns of fact_sales are created
-- separately, AFTER the bulk data load (see src/load.py). Building them
-- after loading avoids the overhead of updating an index on every single
-- row insert - see the comment in load.py for the full explanation.
